import * as vscode from 'vscode';
import { GoogleAuth } from 'google-auth-library';

export function activate(context: vscode.ExtensionContext) {
    console.log('OpenCode Vertex Agent is now active!');

    const provider = new VertexChatViewProvider(context.extensionUri);
    
    context.subscriptions.push(
        vscode.window.registerWebviewViewProvider(
            'vertex-agent-chat', 
            provider
        )
    );

    let disposable = vscode.commands.registerCommand('opencode-vertex.askAgent', () => {
        vscode.commands.executeCommand('vertex-agent-chat.focus');
    });

    context.subscriptions.push(disposable);
}

class VertexChatViewProvider implements vscode.WebviewViewProvider {
    public static readonly viewType = 'vertex-agent-chat';
    private _view?: vscode.WebviewView;

    constructor(private readonly _extensionUri: vscode.Uri) {}

    public resolveWebviewView(
        webviewView: vscode.WebviewView,
        context: vscode.WebviewViewResolveContext,
        _token: vscode.CancellationToken,
    ) {
        this._view = webviewView;
        webviewView.webview.options = { enableScripts: true };

        webviewView.webview.html = this._getHtmlForWebview();

        webviewView.webview.onDidReceiveMessage(async data => {
            switch (data.type) {
                case 'askQuestion':
                    {
                        const answer = await this.queryVertexAISearch(data.text);
                        this._view?.webview.postMessage({ type: 'addResponse', text: answer });
                        break;
                    }
            }
        });
    }

    private async queryVertexAISearch(query: string): Promise<string> {
        const config = vscode.workspace.getConfiguration('opencodeVertex');
        const projectId = config.get<string>('projectId');
        const dataStoreId = config.get<string>('dataStoreId');
        const location = config.get<string>('location') || 'global';

        if (!projectId || !dataStoreId) {
            return "ERROR: Missing Project ID or Data Store ID. Please configure them in VS Code Settings (Ctrl+, search 'opencodeVertex').";
        }

        try {
            // Get Current Open File Context (Agentic behavior)
            const editor = vscode.window.activeTextEditor;
            let fileContext = '';
            if (editor) {
                const doc = editor.document;
                const selection = editor.selection;
                const text = selection.isEmpty ? doc.getText() : doc.getText(selection);
                fileContext = `\n\n--- Current File Context (${doc.fileName}) ---\n${text.substring(0, 1500)}...`;
            }

            // Authentication to burn $1000 GenAI App Builder credits
            const auth = new GoogleAuth({
                scopes: ['https://www.googleapis.com/auth/cloud-platform']
            });
            const client = await auth.getClient();
            const token = await client.getAccessToken();

            // Discovery Engine API (GenAI App Builder) endpoint
            // THIS is what consumes the Vertex AI Search credits!
            const endpoint = `https://discoveryengine.googleapis.com/v1alpha/projects/${projectId}/locations/${location}/collections/default_collection/dataStores/${dataStoreId}/servingConfigs/default_search:search`;

            // We augment the search query with agentic context
            const augmentedQuery = `${query} ${fileContext}`;

            const body = {
                query: augmentedQuery.substring(0, 1000), // Max query length
                pageSize: 5,
                contentSearchSpec: {
                    summarySpec: {
                        summaryResultCount: 5,
                        includeCitations: true,
                        ignoreAdversarialQuery: true,
                        ignoreNonSummarySeekingQuery: true
                    },
                    snippetSpec: { returnSnippet: true }
                }
            };

            const response = await fetch(endpoint, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${token.token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(body)
            });

            if (!response.ok) {
                const err = await response.text();
                return `Vertex API Error: ${response.status} - ${err}`;
            }

            const data: any = await response.json();
            
            let finalOutput = "";
            
            // Return Grounded Summary generated by GenAI App Builder
            if (data.summary && data.summary.summaryText) {
                finalOutput = `**Generated Summary:**\n${data.summary.summaryText}\n\n`;
            } else if (data.results && data.results.length > 0) {
                finalOutput = `*Found ${data.results.length} relevant documents.*\n\n**Top Snippet:**\n${data.results[0].document.derivedStructData.snippets[0].snippet}\n\n`;
            } else {
                finalOutput = "I searched your GenAI Data Store, but couldn't find relevant internal knowledge for this query.\n\n";
            }

            if (fileContext) {
                finalOutput += `*(Agent utilized current file context from VS Code)*`;
            }

            return finalOutput;

        } catch (error: any) {
            return `GCP Connection Error: ${error.message}\nMake sure you ran 'gcloud auth application-default login' on your machine.`;
        }
    }

    private _getHtmlForWebview() {
        return `<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Vertex Agent</title>
            <style>
                body { font-family: var(--vscode-font-family); padding: 10px; display: flex; flex-direction: column; height: 100vh; }
                #chat { flex-grow: 1; overflow-y: auto; margin-bottom: 10px; }
                .message { margin-bottom: 15px; padding: 10px; border-radius: 5px; }
                .user { background: var(--vscode-editor-selectionBackground); border-left: 3px solid var(--vscode-editor-selectionHighlightBackground); }
                .agent { background: var(--vscode-editor-inactiveSelectionBackground); border-left: 3px solid var(--vscode-textLink-foreground); white-space: pre-wrap; }
                textarea { width: 100%; padding: 8px; border: 1px solid var(--vscode-input-border); background: var(--vscode-input-background); color: var(--vscode-input-foreground); margin-bottom: 10px; resize: vertical; }
                button { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; padding: 8px 15px; cursor: pointer; width: 100%; }
                button:hover { background: var(--vscode-button-hoverBackground); }
                .loader { display: none; font-style: italic; color: var(--vscode-descriptionForeground); margin-bottom: 10px; }
            </style>
        </head>
        <body>
            <h3>OpenCode: GenAI App Builder</h3>
            <div id="chat"></div>
            <div id="loader" class="loader">Agent is searching Vertex AI (burning credits)...</div>
            <textarea id="prompt" rows="3" placeholder="Ask about your codebase..."></textarea>
            <button id="send">Send to Vertex AI</button>

            <script>
                const vscode = acquireVsCodeApi();
                const chat = document.getElementById('chat');
                const prompt = document.getElementById('prompt');
                const loader = document.getElementById('loader');

                document.getElementById('send').addEventListener('click', () => {
                    const text = prompt.value.trim();
                    if (!text) return;
                    
                    chat.innerHTML += '<div class="message user"><b>You:</b><br/>' + text + '</div>';
                    prompt.value = '';
                    loader.style.display = 'block';
                    
                    vscode.postMessage({ type: 'askQuestion', text: text });
                    chat.scrollTop = chat.scrollHeight;
                });

                window.addEventListener('message', event => {
                    const message = event.data;
                    switch (message.type) {
                        case 'addResponse':
                            loader.style.display = 'none';
                            chat.innerHTML += '<div class="message agent"><b>Vertex Agent:</b><br/>' + message.text + '</div>';
                            chat.scrollTop = chat.scrollHeight;
                            break;
                    }
                });
            </script>
        </body>
        </html>`;
    }
}

export function deactivate() {}